spring.application.name=Violation-Management-System
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=12100

# DB
## LiquiBase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml